version: "3.7"
services:

  nginx:
    image: nginx:1.20.1
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-app.conf/etc/nginx/conf.d/app.conf:ro
    ports:
      - "80:80"
    networks:
      - po8klasie

  frontend:
    image: ghcr.io/po8klasie/po8klasie:${FRONTEND_TAG}
    networks:
      - po8klasie
    environment:
      API_URL: "/api"
      GRAPHQL_ENDPOINT: "/api/graphql/"
    env_file:
      - secrets.env
    depends_on:
      - backend

  backend:
    image: ghcr.io/po8klasie/po8klasie-api:${BACKEND_TAG}
    volumes:
      - media:/opt/warsawlo/media
    networks:
      - po8klasie
    environment:
      DJANGO_SETTINGS_MODULE: warsawlo.settings
      DJANGO_DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1 test.po8klasie.pl po8klasie.pl"
      SECURE_COOKIES: "True"
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: warsawlo
      SQL_USER: warsawlo
      SQL_PASSWORD: warsawlo
      SQL_HOST: "db"
      UWSGI_WORKERS_COUNT: 1
    env_file:
      - secrets.env
    depends_on:
      - db

  db:
    image: postgres:12.2
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: warsawlo
      POSTGRES_PASSWORD: warsawlo
      POSTGRES_DB: warsawlo
    networks:
      - po8klasie

networks:
  po8klasie:

volumes:
  db-data:
  media:
