name: Update test

on:
  push:
    branches:
    - master

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: instance-1
  GCE_INSTANCE_ZONE: europe-west4-a

jobs:
  update-test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.1.0

    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        project_id: ${{ secrets.GCE_PROJECT }}

    - name: Turnstyle
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Print secrets
      run: |
        echo "
        DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
        PUBLIC_SENTRY_DSN=${PUBLIC_SENTRY_DSN}
        SENTRY_DSN=${SENTRY_DSN}
        MATOMO_BASE_URL=${MATOMO_BASE_URL}
        MATOMO_SITE_ID=${MATOMO_SITE_ID}
        " > secrets.env
      shell: bash
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        PUBLIC_SENTRY_DSN: ${{ secrets.PUBLIC_SENTRY_DSN }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        MATOMO_BASE_URL: ${{ secrets.MATOMO_BASE_URL }}
        MATOMO_SITE_ID: ${{ secrets.MATOMO_SITE_ID_TEST }}
        
    - name: Clean ssh keys
      run: |-
        # https://github.com/kyma-project/test-infra/issues/93#issuecomment-457263589
        for i in $(gcloud compute os-login ssh-keys list | grep -v FINGERPRINT); do \
            echo "Removing ssh key"; \
            gcloud compute os-login ssh-keys remove --key $i || true; \
        done

    - name: Upload secrets
      run: |-
        gcloud compute scp --zone ${GCE_INSTANCE_ZONE} secrets.env ${GCE_INSTANCE}:/home/mlazowik/infra/app/

    - name: Deploy
      run: |-
        gcloud compute ssh --zone ${GCE_INSTANCE_ZONE} ${GCE_INSTANCE} -- \
          -tt -C "cd /home/mlazowik/infra/app && git pull && ln -sf .env.test .env && bash update-all.sh && yes | docker system prune"

    - name: Purge cache
      uses: jakejarvis/cloudflare-purge-action@v0.3.0
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
